apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: k8s-orchestrate-
spec:
  arguments:
    parameters:
      - name: releaseit_flags
        value: ""
      - name: release_increment
        value: ""

  entrypoint: k8s-orchestrate

  podGC:
    # Pod GC strategy must be one of the following:
    # * OnPodCompletion - delete pods immediately when pod is completed (including errors/failures)
    # * OnPodSuccess - delete pods immediately when pod is successful
    # * OnWorkflowCompletion - delete pods when workflow is completed
    # * OnWorkflowSuccess - delete pods when workflow is successful
    strategy: OnWorkflowSuccess

  templates:
    - name: k8s-orchestrate
      steps:
        - - name: build
            template: build
            arguments:
              parameters:
                - name: releaseit_flags
                  value: "{{workflow.parameters.releaseit_flags}}"
                - name: release_increment
                  value: "{{workflow.parameters.release_increment}}"
    - name: build
      inputs:
        parameters:
          - name: releaseit_flags
          - name: release_increment

      resource:
        action: create
        successCondition: status.succeeded > 0
        failureCondition: status.failed > 0
        manifest: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            generateName: build-
          spec:
            ttlSecondsAfterFinished: 100
            backoffLimit: 0
            template:
              metadata:
                name: build
              spec:
                volumes:
                  - name: github-ssh-key
                    secret:
                      secretName: github
                      defaultMode: 0600
                  - name: npm-secrets
                    secret:
                      secretName: npm
                      defaultMode: 0600
                  - name: gitconfig
                    secret:
                      defaultMode: 0600
                      secretName: gitconfig
                containers:
                  - name: design-system-builder
                    image: agolub/design-system-builder:0.1.0
                    imagePullPolicy: Always
                    volumeMounts:
                      - name: github-ssh-key
                        readOnly: true
                        mountPath: "/root/.ssh"
                      - name: npm-secrets
                        readOnly: true
                        mountPath: "/usr/src/secrets"
                      - name: gitconfig
                        mountPath: "/root/.gitconfig"
                        readOnly: true
                    env:
                      - name: GITHUB_ACCESS_TOKEN
                        valueFrom:
                          secretKeyRef:
                            name: github-access-token
                            key: token
                      - name: NPM_TOKEN
                        valueFrom:
                          secretKeyRef:
                            name: npm-token
                            key: token
                      - name: DOCS_API_KEY
                        valueFrom:
                          secretKeyRef:
                            name: docs-api-key
                            key: token
                      - name: RELEASEIT_FLAGS
                        value: "{{inputs.parameters.releaseit_flags}}"
                      - name: RELEASE_INCREMENT
                        value: "{{inputs.parameters.release_increment}}"
                    command: ["/bin/sh"]
                    args: [
                      "-c",
                      ". ./run.sh"
                    ]
                restartPolicy: Never
      outputs:
        parameters:
          - name: job-name
            valueFrom:
              jsonPath: "{.metadata.name}"
          - name: job-uid
            valueFrom:
              jsonPath: "{.metadata.uid}"
