name: Export & Build

on:
  push:
    branches: [ main ]

jobs:
  export:
    runs-on: agolub/figma-exporter-workflow-executor:1.0.0

    steps:
    - name: Export 4.5 System Icons
      run: |
       /bin/bash /srv/scripts/run.sh
      with:
        API_SERVER_URL: https://g4zv2x9d77.execute-api.us-east-1.amazonaws.com/prod
		    ARGO_SERVER_URL: https://argocd.workers.design.infor.com
		    API_KEY: ${{ secrets.API_KEY }}
		    FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
		    S3_UPLOADS_BUCKET_NAME: infor-design-assets-downloads
		    FIGMA_FILE_KEY: XWg7HKWXuEa4O4pEoAGmYi
		    COL_ID: 217
		    COL_NAME_FORMATTED: ids_assets_library_v4_5_system_icons
		    PAGE_ID: 0:1
		    PUBLISHED: 1
		    ITEM_TYPE: component
		    STYLE_TYPES: 0
		    CONFIGS: %7B%22replace_prop_values%22%3A%5B%7B%22order%22%3A0%2C%22desc%22%3A%22set%20all%20strokes%20to%20currentColor%22%2C%22tag_name%22%3A%22path%22%2C%22prop%22%3A%22stroke%22%2C%22prop_value_regex%22%3A%22%28%23606066%29%22%2C%22replace_with%22%3A%22currentColor%22%2C%22replace_occurance%22%3A%22all%22%7D%2C%7B%22order%22%3A1%2C%22desc%22%3A%22all%20fills%20to%20currentColor%22%2C%22tag_name%22%3A%22path%22%2C%22prop%22%3A%22fill%22%2C%22prop_value_regex%22%3A%22%28%23606066%29%22%2C%22replace_with%22%3A%22currentColor%22%2C%22replace_occurance%22%3A%22all%22%7D%2C%7B%22order%22%3A2%2C%22desc%22%3A%22set%20all%20strokes%20to%20currentColor%22%2C%22tag_name%22%3A%22rect%22%2C%22prop%22%3A%22stroke%22%2C%22prop_value_regex%22%3A%22%28%23606066%29%22%2C%22replace_with%22%3A%22currentColor%22%2C%22replace_occurance%22%3A%22all%22%7D%2C%7B%22order%22%3A3%2C%22desc%22%3A%22all%20fills%20to%20currentColor%22%2C%22tag_name%22%3A%22rect%22%2C%22prop%22%3A%22fill%22%2C%22prop_value_regex%22%3A%22%28%23606066%29%22%2C%22replace_with%22%3A%22currentColor%22%2C%22replace_occurance%22%3A%22all%22%7D%5D%2C%22remove_props%22%3A%5B%22fill%22%2C%22stroke%22%5D%2C%22remove_props_from%22%3A%22svg%22%2C%22unique_ids%22%3Atrue%2C%22create_png%22%3Atrue%2C%22group_fill_rule%22%3Atrue%2C%22name_style%22%3A%22dash%22%7D
		    POPULATE_WORK_QUEUE_JOB_ID: 46
		    CONSUME_QUEUE_JOB_ID: 47
		    EXPORT_JOB_ID: 45
		    GROUP_IDS: none
